### ISSUE TITLE
.NET RLBot does not inform bots of shutdown

### ISSUE THREAD

**Issue by alion02** [RLBot/RLBot#228]
This means that bots cannot get rid of unmanaged resources or do other types of de-initialization.

**Comment by alion02** [comment]
Probably the best option is to expose an `abstract` method or make the `Bot` class `IDisposable`.

**Comment by TheBlocks** [comment]
Adding the IDisposable interface would make it a breaking change, which is something we absolutely do not want. Adding an abstract method would also make it a breaking change. In these 2 situations the user _has to_ implement a new termination method. This is undesirable.

We want something where the user does not have to add anything should they not wish to add de-initialising code, but they could add it if they wanted to. It would be best to make the method called on bot termination overrideable instead of abstract or IDisposable. I suggest making a method `void OnBotRetire()` in the `Bot` class, which gets called when the bot gets terminated. It would get called at the top of the `BotManager.StopBotProcess` method: https://github.com/RLBot/RLBot/blob/master/src/main/cs/RLBotDotNet/RLBotDotNet/Manager/BotManager.cs#L126.

**Comment by alion02** [comment]
How about simply make the `Bot` `IDisposable`, but with a `public virtual void Dispose() { return; }` so it's not a breaking change? I think following conventions is a good idea, and I see no point in not using the `IDisposable` interface.
