### ISSUE TITLE
BaseSubprocessAgent relative path issue

### ISSUE THREAD

**Issue by whatisaphone** [RLBot/RLBot#287]
I realized a deficiency in `BaseSubprocessAgent` while helping people set up for the tourney yesterday. Right now, it looks for the configured exe implicitly relative to the process cwd. Instead, it should look for it explicitly relative to the path of the `.cfg` file that contains the path. That way, you can move the directory containing the .cfg and .exe wherever you want, and it will still work. This should be fixed before the next tournament.

**Comment by tarehart** [comment]
You're in luck because I just added a "getpath" function to the config header class which can be used right here: https://github.com/RLBot/RLBot/blob/master/src/main/python/rlbot/agents/base_subprocess_agent.py

It will resolve paths relative to the config file. https://github.com/RLBot/RLBot/blob/master/src/main/python/rlbot/parsing/custom_config.py

**Comment by whatisaphone** [comment]
That is very relevant, looks like it will be a 4-character diff then!

**Comment by ima9rd** [comment]
Should be fixed now 👍

**Comment by whatisaphone** [comment]
Thanks!
