### ISSUE TITLE
RLBot_Injector flagged as virus.

### ISSUE THREAD

**Issue by nuvious** [RLBot/RLBot#352]
Looked through the source for the RLBot injector and am not concerned about it actually being a virus, but wanted to highlight the fact it's being flagged as a false-positive by several virus scanning vendor. My reproduction steps are as follows with my experience using python.

1. Install rlbot via pip.
2. Upload the site-packages/rlbot/dll/RLBot_Injector.exe to virustotal.com (or it'll already be flagged by the virus scanner).
3. You'll see the vendors which currently flag the executable.
4. With my virus scanning vendor, flagging the file as safe doesn't seem to fix the issue unfortunately.

Possible mitigation is to sign the executable with a certificate via sign-tool.exe. A self-signed cert may be enough to stop the false positives but I know some virus scanning vendors do not recognize self signed certs.

**Comment by tarehart** [comment]
Thanks for the report!

We've been working around this for a while by directing people to https://github.com/RLBot/RLBot/wiki/Antivirus-Notes, which is obviously not ideal.

I believe @ccman32 has submitted the file to Microsoft to be vetted and that helped a bit. He's the expert on this, and I'll defer to him on whether he thinks a self-signed cert is worth a shot.

**Comment by ccman32** [comment]
@nuvious Are you sure that signing it with a self-signed cert would make any difference regarding false positives? It sounds somewhat ridiculous to me because it changes nothing about the application's behavior and every malware developer could do the exact same thing to his malware.
Anyway, we are already keeping track of current false positives from different antivirus software and submitting the file for manual analysis to an antivirus vendor in case a too large number of users runs into issues because of that specific antivirus vendor.

**Comment by nuvious** [comment]
@nevercast You can use https://www.virustotal.com/#/home/upload to see which antiviruses are being flagged. About 1/3 of them do at the moment and you can also mark your uploads as safe.

@ccman32 It does sound ridiculous, but have read that some virus scanners ignore anything signed and don't bother checking the cert. This make sense for some legacy applications that were signed with valid certs at some point but later had their certificate expire. I'll try to dig up a formal reference but can't remember the key-word-tricky-phase that I used in search when I last looked this up so for now take that recommendation with a grain of salt.

**Comment by nuvious** [comment]
Did some more reading, and the code signing thing only works for some anti-virus software and it's actually being criticized in the cyber security community. Best bet is to submit to the whitelist pages for evaluation. I did for my antivirus software.

**Comment by nuvious** [comment]
Bitdefender. I’ve already submitted a whitelist request when it first came up. Sorry about not noticing that you had that mentioned in your Wiki. A lot of virus scanners are behavior driven and don’t know the difference between a dll injector from a piece of malware vs a dll injector that’s legit. Unfortunately since I work at a BYOD place, I can’t uninstall my virus scanner by policy so have to try to get this workaround through.

**Comment by ccman32** [comment]
@nuvious Bitdefender does currently not seem to detect the injector anymore so I guess that the issue is solved for you? We will not be actively submitting whitelist requests to all antivirus vendors as long as there is no significant number of rlbot users running into issues with their antivirus software, it's just too much of a hassle and every single update of the injector will require us to repeat the entire process again.

**Comment by nuvious** [comment]
I noticed it the other day myself. I guess we can close the issue but maybe add a section to the readme nodding to the steps I took as a recommendation for those willing to take the leap. It could be just a single line nodding to submitting the file to a white list request. Change to the readme or not feel free to close it.

**Comment by martmists** [comment]
This will no longer be an issue once the official Bot API gets implemented.

**Comment by TheBlocks** [comment]
We are not using DLL injection anymore, so this is no longer an issue.
