### ISSUE TITLE
AttributeError: libRLBotInterface.so: undefined symbol: StartTcpCommunication

### ISSUE THREAD

**Issue by MatthewScholefield** [RLBot/RLBot#532]
I'm getting the following error whenever it initiates the communication with RocketLeague:
```
AttributeError: .../site-packages/rlbot/dll/libRLBotInterface.so: undefined symbol: StartTcpCommunication
```
I also tried the latest version on master in case a recent change fixed it, but with no luck.

I'm running on Linux via Proton and `prime-run`. Initially I suspected that this is because of a change in the closed source library, but it looks like the `.dll` was just updated 3 hours ago even though the `.so` was only updated 4 months ago. Is it possible that the RLBot Linux install instructions need to be updated to run using wine so that it uses the `.dll`?

**Comment by tarehart** [comment]
Thanks for reporting! The change to the .so was premature / unintentional, I'll revert soon. Sorry about that!

**Comment by tarehart** [comment]
Whoops, I was wrong about what the issue is. You'll actually need to downgrade RLBot to 1.48.1 until I bring Linux up to par, it'll take me some time.

You could do something like `python3 -m pip install rlbot==1.48.1`. If you have an auto-upgrade script that uses a requirements.txt, you may need to change the rlbot line to rlbot==1.48.1.

Or you can try to make it use the dll as you mentioned.

**Comment by tarehart** [comment]
Nevermind, I went ahead and rolled back. The version 1.48.3 should be back to working on Linux.
