### ISSUE TITLE
Retrieving Image instead of coordinates

### ISSUE THREAD

**Issue by NaxAlpha** [RLBot/RLBot#554]
Hi, I want to ask if it is possible to retrieve the image/screen instead of coordinate information.

**Comment by ViliamVadocz** [comment]
Not with this package. This is an official Psyonix-supported API and the information we get is curated by them. With enough coding experience you can easily get the screen, but why would you want that? That just adds a whole other layer of complexity.

**Comment by NaxAlpha** [comment]
While standard APIs provide all the necessary information to build solid agents, most of the reinforcement learning literature relies on visual information. Secondly, in order to build agents which learn from experiences (imitation learning and other similar techniques which use existing data), it becomes really hard to get re-recorded this type of coordinate data from experts, etc than to just get a youtube video.

**Comment by Darxeal** [comment]
Luckily in Rocket League there is plenty of this type of coordinate data from experts, because the game has a replay system and there are huge databases of them, like [calculated.gg](https://calculated.gg/). And there are tools to parse and analyze them, like [carball](https://github.com/SaltieRL/carball). Learning from them hasn't been very successful yet, but I can't imagine it's worse than training on video data. But I would be happy if you prove me wrong.

**Comment by NaxAlpha** [comment]
The last time I checked, the data stored in `calculated.gg` and decoding it with carball is not very accurate in terms of time intervals. I think it also happens in RLBot i.e., the rate at which we get data from the game may not be very consistent but that is another problem.

**Comment by MarcoMeter** [comment]
Are there any news on this concern?

I'd really appreciate it, because I've got a Deep Reinforcement Learning training pipeline that trains a bot on goalie and striker tasks in a Unity-based Rocket League environment. The trained behavior can be successfully transferred to the true domain of Rocket League. I really would like the agent to sense the same information as a human player as I'm specializing on partially observable environments. (More information on this sim-to-sim transfer will be available once my paper is accepted.)

**Comment by tarehart** [comment]
I think we're unlikely to ever provide a screen image as part of RLBot, it's outside of our mission. As @ViliamVadocz alluded to, our interface to Rocket League is purely through the API Psyonix provided to us, and we'd like to continue in that manner for a few reasons:
- When the API is active on the Rocket League side, matchmaking is disabled. That enforcement creates an anti-cheat measure that both we and Psyonix are comfortable with.
- Our volunteer maintainers are pretty busy with the features we've already got / it's already challenging to make changes that are binary compatible with existing bots.

So even if somebody were to make a pull request with this feature, we'd probably choose to reject it. Image-based projects are definitely cool, but not a good fit for our main branch in my opinion.

**Comment by MarcoMeter** [comment]
We just got our paper accepted at the Conference on Games on training goalkeeping and striking agents, which were trained in a Unity-based adaption of the true Rocket League game.

"On the Verge of Solving Rocket League using Deep Reinforcement Learning and Sim-to-sim Transfer"
https://arxiv.org/abs/2205.05061
Videos
https://www.youtube.com/watch?v=8k9FNxIU0KQ&list=PL2KGNY2Ei3ix7Vr_vA-ZgCyVfOCfhbX0C&index=4

It's not just about cool stuff that people could do with image-based observations. We actually do serious research, which goes far beyond just video games. I hope that our work will reach Psyonix to change their mind on the underlying API. There are so many great opportunities to pursue if image and audio would be available.
