### ISSUE TITLE
Installation: ModuleNotFoundError: No module named 'rlbot_gui'

### ISSUE THREAD

**Issue by CoffeeArmor** [RLBot/RLBot#562]
Hello, total noob over here (i'm sorry)

It's been two days, I'm not able to launch RLBot.

First time it worked (i saw the interface and installed the bot packages) but the game did not run - think it was a problem with my antivirus so I added an exception as the troubleshooting says. I tried again and I got this message from the rlbotgui.exe :

![cmd-rlgui](https://user-images.githubusercontent.com/90412222/132733730-3fd87485-a2ce-4ea0-8b7b-5ff05a2b087e.png)
 
Already followed the troubleshooting page and the "installation errors" guide as well as the "'pip 'is not recognized as an internal or external command" guide. Same message each time. I've deleted Rlbot and reinstalled it several times. 

Couldn't find the issue elsewhere. Does anyone know how to fix this ? I'm very frustrated that it worked partially at the start and now I can't even get to the GUI. 

Thanks in advance !
(Sorry if it's a stupid issue)

**Comment by robbai** [comment]
Hey, I recommend linking/describing your issue in the #issues-and-bugs channel in the [Discord server](https://discord.com/invite/nhdwbSz), you may find help there quicker

**Comment by SnowSnakz** [comment]
I don't know if you were able to fix the issue, but sense I had the same issue and this threat currently doesn't have an answer I will post mine.

What happened to me was that the pip install script that runs at first launch wasn't downloading things correctly occasionally, and when that happened it would just stop downloading the rest of the packages and try to launch the program. The reason why 'rlbot_gui' doesn't exist is because it never fully downloaded before it was trying to be used. I was able to solve this by just relaunching the program until it successfully installed everything.

**Comment by VirxEC** [comment]
If you're still having issues, please visit the #issues-and-bugs channel in our [Discord server](https://discord.com/invite/nhdwbSz) for help.

**Comment by TLRplayz** [comment]
Did this issue get resolved because I'm running into the same problem and have very very bad wifi. The download speed at its worst goes it 6kb/second

**Comment by redd-rl** [comment]
this isn't some major death issue, it's just the installer shoots itself in the foot on occasion and the fix is ridiculously simple.
